title: John Doe # your name (or website title) here
logo: "logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor of Computer Science
  <br><br>
  Data Enthusiast
  <br><br>
  <a href="https://www.linkedin.com/in/aar-riana/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-BNK498QR11 # your Google Analytics tracking ID here
