title: Aar Riana # your name (or website title) here
logo: "logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center> 
  [![See My LinkedIn](https://img.shields.io/badge/LinkedIn-blue?logo=Linkedin)](https://www.linkedin.com/in/aar-riana/)
  [![See My Github](https://img.shields.io/badge/Github-black?logo=github)](https://github.com/rianaaar)
  </center>
  <br>
  Bachelor of Computer Science
  <br>
  Data Enthusiast
  <br>
  
theme: jekyll-theme-minimal
google_analytics: G-BNK498QR11 # your Google Analytics tracking ID here
